/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.theveganrobot.cvcamera.jni;

public interface cvcameraConstants {
  public final static int DETECT_CANNY = cvcameraJNI.DETECT_CANNY_get();
  public final static int DETECT_HOUGH_LINES = cvcameraJNI.DETECT_HOUGH_LINES_get();
  public final static int DETECT_HOUGH_CIRCLES = cvcameraJNI.DETECT_HOUGH_CIRCLES_get();
}
